from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.orm import Session
from typing import List, Optional
from ..database import get_db
from ..models import Paper, Version, User, InferenceTask
from ..schemas import (
    PaperCreate, PaperResponse, PaperWithVersions,
    VersionResponse, UploadResponse
)
from ..services.drive_service import upload_file_to_drive
from ..services.queue_service import push_inference_task

router = APIRouter(prefix="/papers", tags=["papers"])


@router.post("/", response_model=PaperResponse)
def create_paper(paper: PaperCreate, user_id: int, db: Session = Depends(get_db)):
    """Create a new paper."""
    user = db.query(User).filter(User.user_id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    new_paper = Paper(
        user_id=user_id,
        title=paper.title,
        target_conference=paper.target_conference,
        status="Draft"
    )
    db.add(new_paper)
    db.commit()
    db.refresh(new_paper)
    return new_paper


@router.get("/", response_model=List[PaperResponse])
def get_papers(
    user_id: Optional[int] = None,
    status: Optional[str] = None,
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """Get papers with optional filters."""
    query = db.query(Paper)
    if user_id:
        query = query.filter(Paper.user_id == user_id)
    if status:
        query = query.filter(Paper.status == status)
    return query.offset(skip).limit(limit).all()


@router.get("/{paper_id}", response_model=PaperWithVersions)
def get_paper(paper_id: int, db: Session = Depends(get_db)):
    """Get paper with all versions."""
    paper = db.query(Paper).filter(Paper.paper_id == paper_id).first()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")
    return paper


@router.post("/{paper_id}/upload", response_model=UploadResponse)
async def upload_paper_version(
    paper_id: int,
    file: UploadFile = File(...),
    conference_rule_id: str = Form(default="GENERAL"),
    db: Session = Depends(get_db)
):
    """
    Upload a new version of a paper.
    This triggers the async inference pipeline.
    """
    # Validate paper exists
    paper = db.query(Paper).filter(Paper.paper_id == paper_id).first()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")

    # Validate file type
    file_ext = file.filename.split('.')[-1].lower() if file.filename else ''
    if file_ext not in ['pdf', 'tex']:
        raise HTTPException(status_code=400, detail="Only PDF and TeX files are allowed")

    # Get user info for folder structure
    user = db.query(User).filter(User.user_id == paper.user_id).first()

    # Read file content
    file_content = await file.read()

    # Upload to Google Drive
    try:
        drive_file_id = upload_file_to_drive(
            file_content=file_content,
            file_name=file.filename,
            mime_type=file.content_type or 'application/octet-stream',
            student_name=user.name,
            paper_title=paper.title
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to upload to Drive: {str(e)}")

    # Create version record (version_number is auto-generated by trigger)
    new_version = Version(
        paper_id=paper_id,
        drive_file_id=drive_file_id,
        file_name=file.filename,
        file_type=file_ext
    )
    db.add(new_version)
    db.commit()
    db.refresh(new_version)

    # Update paper status
    paper.status = "Processing"
    db.commit()

    # Create inference task
    inference_task = InferenceTask(
        version_id=new_version.version_id,
        status="Pending",
        conference_rule_id=conference_rule_id
    )
    db.add(inference_task)
    db.commit()
    db.refresh(inference_task)

    # Push to Redis queue
    task_data = {
        "task_id": inference_task.task_id,
        "version_id": new_version.version_id,
        "paper_id": paper_id,
        "file_id": drive_file_id,
        "conference_rule_id": conference_rule_id
    }
    push_inference_task(task_data)

    return UploadResponse(
        message="File uploaded successfully. Analysis in progress.",
        paper_id=paper_id,
        version_id=new_version.version_id,
        task_id=inference_task.task_id
    )


@router.get("/{paper_id}/versions", response_model=List[VersionResponse])
def get_paper_versions(paper_id: int, db: Session = Depends(get_db)):
    """Get all versions of a paper."""
    paper = db.query(Paper).filter(Paper.paper_id == paper_id).first()
    if not paper:
        raise HTTPException(status_code=404, detail="Paper not found")
    return paper.versions
